Controllers/HRAdminController.cs
using Microsoft.AspNetCore.Mvc;
using UCITMS.Common;
using UCITMS.Data.IRepositories;
using UCITMS.Data.Repositories;
using UCITMS.Models;


namespace UCITMS.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class HRAdminController : ControllerBase
    {
        private readonly IHRAdminRepository _hrAdminRepository;
        private readonly INotificationRepository _notificationRepository;
        private readonly IManagerDelegateRepository _managerDelegateRepository;
        private IAuthorizationRepository _authorizationRepository;

        #region Constructor
        public HRAdminController(IHRAdminRepository hrAdminRepository, INotificationRepository notificationRepository, IManagerDelegateRepository managerDelegateRepository, IAuthorizationRepository authorizationRepository)
        {
            _hrAdminRepository = hrAdminRepository;
            _notificationRepository = notificationRepository;
            _managerDelegateRepository = managerDelegateRepository;
            _authorizationRepository = authorizationRepository;
        }
        #endregion

        #region GET API for Primary Approver Dropdown
        [AppAuthorizationFilter(AutherizationType.Menu, Item.Assign_Approver)]
        [HttpGet("getallmanagers")]
        public async Task<IActionResult> GetAllManagersInfo()
        {
            List<GetAllManagersDTO> managersInfo = await
                _managerDelegateRepository.GetAllManagersInfoAsync();
            return Ok(managersInfo);
        }
        #endregion

        #region GET API for Secondary Approver Dropdown
        [AppAuthorizationFilter(AutherizationType.Menu, Item.Assign_Approver)]

        [HttpGet("GetAllUsers")]
        public async Task<ActionResult<List<UserDTO>>> GetAllUsers()
        {
            //int currentUserId = (int)UserSession.GetUserId(HttpContext);
            var users = await _hrAdminRepository.GetAllUsers();
            if (users == null || users.Count == 0)
            {
                return NotFound("No users found.");
            }
            return Ok(users);
        }
        #endregion

        #region Get API for AssignApprover

        [AppAuthorizationFilter(AutherizationType.Menu, Item.Assign_Approver)]
        [HttpGet("getallusermanagerinfo")]
        public async Task<IActionResult> GetAllUserManagerInfo()
        {
            List<GetUserManagerDTO> userManagerInfo = await _hrAdminRepository.GetUserManagerInfoAsync();
            return Ok(userManagerInfo);
        }
        #endregion

        #region POST API for AssignApprover
        [AppAuthorizationFilter(AutherizationType.Menu, Item.Assign_Approver)]
        [HttpPost("save")]
        public async Task<IActionResult> AddOrUpdateApprovers([FromBody] PostUserManagerDTO usermanager)
        {
            
            usermanager.ModUserID = UserSession.GetUserId(HttpContext);
            ValidateApproverDTO obj = await _hrAdminRepository.AddOrUpdateApproversAsync(usermanager);
            if (obj.Status == -1 || obj.Status == -2 || obj.Status == -3 || obj.Status == -4)
            {
                return BadRequest(obj);
            }
            else if(obj.Status == 1)
            {
                return Ok(obj);
            }
            else
            {
                return StatusCode(StatusCodes.Status500InternalServerError, new { Status = 0, Message = "An unexpected error occurred." });
            }

        }
        #endregion

        #region GET API for Users With No Approver List
        [HttpGet("getnoapproverlist")]
        public async Task<IActionResult> GetNoApproverList()
        {
            var userNoApproverCount = await _hrAdminRepository.GetListNoApproverAsync();
            return Ok(userNoApproverCount);
        }
        #endregion

        #region Send Pending Approval Email
        [AppAuthorizationFilter(AutherizationType.Menu, Item.Approval_Status)]
      
        [HttpPost("sendpendingEmail")]
        public IActionResult SendPendingEmail([FromBody] NotifyApproverPost obj)
        {
            int moduser = (int)UserSession.GetUserId(HttpContext);

            if (!_authorizationRepository.TimesheetAccess(AutherizationType.CanNotifyApprover, obj.TimesheetID, moduser))
            {
                return Unauthorized(new { error = "You are not authorized to notify this manager!!" });
            }

            bool isSent = _notificationRepository.SendNotifyApprover(obj.ManagerId, obj.UserID, obj.TimesheetID);
            if (isSent)
            {
                return Ok("Notification sent successfully.");
            }
            else {
                return BadRequest("Failed to send notification");
            }
        }


        #endregion

        #region Save Notified Logs
        [AppAuthorizationFilter(AutherizationType.Menu, Item.Approval_Status)]
        [HttpPost("SaveNotifiedEmailLog")]
        public IActionResult SaveNotifiedEmailLog([FromBody] NotifiedEmailLog model)
        {
            if (model == null)
            {
                return BadRequest("Invalid data.");
            }

            var isSaved = _hrAdminRepository.SaveNotifiedEmailLog(model);

            if (isSaved)
            {
                return Ok(new { Message = "Data saved successfully." });
            }

            return StatusCode(500, "An error occurred while saving the data.");
        }
        #endregion

        #region Get Notified Logs

        [AppAuthorizationFilter(AutherizationType.Menu, Item.Approval_Status)]
        [HttpGet("getnotifieddata")]
        public async Task<ActionResult> GetNotifiedData()
        {
            var timesheets = await _hrAdminRepository.GetNotifiedDataAsync();
            return Ok(timesheets);
        }
        #endregion

    }
}

Views/Shared/PageNotFound.cshtml
<style>
    .fullscreen-center {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        background-color: #f4f4f4;
        font-family: Arial, sans-serif;
        text-align: center;
    }
</style>

<div class="fullscreen-center">
    <div class="ui raised very padded text container segment">
        <img src="/image/404.png" style="width: 200px" />
        <h1 class="ui huge header" style="color: #DB2828;">
            PAGE NOT FOUND
        </h1>
        <div class="ui divider"></div>
        <h3 class="ui header">
            The page you're trying to access has restricted access.
        </h3>
        <h3 class="ui header">
            Please refer to your system administrator.
        </h3>
    </div>
</div>

Views/Shared/_Footer.cshtml
<div class="ui bottom attached menu borderless w-100 p-3">
    <div class="left item">
        <a href="https://netorg207568.sharepoint.com/:u:/r/sites/UCITMS-SupportSite/SitePages/CollabHome.aspx?csf=1&web=1&e=amy1UY" target="_blank" rel="noopener noreferrer">
            <span class="ui medium text" style="color: #0066cc;"><b id="imp-docs">Support Site</b></span>
        </a>
    </div>
    <div class="left item" id="copyright">
        <span class="ui medium text"><b>Copyright <i class="copyright outline icon"></i>2025 UCI</b></span>
    </div>
    <div class="right item">
        <a href="https://forms.office.com/Pages/ResponsePage.aspx?id=c2sTc0wi3ECKjQPmq4kX2LATpgxue-BHnf1rqKAK9dhURTVTOUFVM0VaMlJEQ1JQUUg0VzVRMllIWC4u" target="_blank" rel="noopener noreferrer">
            <span class="ui medium text" style="color: #0066cc;"><b id="contact-admin">Feedback Form</b></span>
        </a>
    </div>
</div>

<style>
    #copyright {
        pointer-events: none;
    }

        #copyright:hover {
            color: inherit !important;
            text-decoration: none !important;
        }

</style>

Views/Shared/_Layout.cshtml
@model UCITMS.Models.UserDTO

@{
    var version = "2.0";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] UCITMS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css?ver=@version" />
    <link rel="stylesheet" href="~/UCITMS.styles.css?ver=@version" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/fomantic-ui@2.9.3/dist/semantic.min.css?ver=@version">
    <link rel="stylesheet" href="https://unpkg.com/ag-grid-community/styles/ag-grid.css?ver=@version">
    <link rel="stylesheet" href="https://unpkg.com/ag-grid-community/styles/ag-theme-alpine.css?ver=@version">
    <link rel="stylesheet" href="~/css/site.css?ver=@version" asp-append-version="true" />
    <script src="https://cdn.jsdelivr.net/npm/dayjs@1/dayjs.min.js?ver=@version"></script>
    <script src="https://cdn.jsdelivr.net/npm/dayjs@1/plugin/utc.js?ver=@version"></script>
    <script>
        dayjs.extend(dayjs_plugin_utc);
    </script>
</head>
<body>
    <div class="container-fullheight">
        <header>
            @await Html.PartialAsync("_Navbar", Model)
            @Html.Partial("_PageLock")


        </header>
        <div class="content-wrapper">
            <div class="sidebar">
                @await Component.InvokeAsync("LeftMenu", new { selectedMenuPath = Context.Request.Path.Value })
            </div>
            <main role="main" class="main-content pb-3">
                @RenderBody()
            </main>
        </div>

        <footer>
            @await Html.PartialAsync("_Footer", Model)
        </footer>
    </div>


    <!-- ag-Grid JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ag-grid/32.3.3/ag-grid-community.noStyle.js?ver=@version"></script>
    <!-- Lodash Library -->
    <script src="https://cdn.jsdelivr.net/npm/lodash/lodash.min.js?ver=@version"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js?ver=@version"></script>
    <script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.9.3/dist/semantic.min.js?ver=@version"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js?ver=@version"></script>
    <script type="module" src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.8.69/pdf.min.mjs?ver=@version"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.5.15/jspdf.plugin.autotable.min.js?ver=@version"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js?ver=@version"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js?ver=@version"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chartjs-plugin-datalabels/2.2.0/chartjs-plugin-datalabels.min.js?ver=@version"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js?ver=@version"></script>
    <script src="~/js/helper.js?ver=@version"></script>
    <script src="~/js/underscore-umd-min.js?ver=@version"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_NavBar.cshtml
@{
    var version = "2.0";
}
@using UCITMS

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Fomantic UI -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.8/dist/semantic.min.css">
    <link rel="stylesheet" href="~/css/Notification.css" />
    <script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.8/dist/semantic.min.js"></script>
    <script src="~/js/notification.js"></script>

    <style>
        .container {
            max-width: 100vw;
            margin: 0;
            padding: 0;
        }

        .ui[class*="top attached"].menu {
            margin-top: 0;
            height: 60px;
            position: fixed;
            z-index: 1000;
        }

        body {
            margin-top: 60px;
        }

        .text {
            font-size: xx-large;
        }

        #logo {
            transition: 250ms ease-in-out;
            margin-left: 10px;
        }

            #logo:hover {
                background: none;
                transform: scale(1.2);
            }


        .ui.menu:not(.vertical) .right.item, .ui.menu:not(.vertical) .right.menu {
            margin-left: 0px !important;
        }

        .ui.menu .right.item {
            display: flex;
            align-items: center;
            justify-content: center;
            position: relative;
        }

        #userPopupContent {
            padding: 5px;
            background-color: white;
            border-radius: 5px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            position: absolute;
            z-index: 1;
        }

        .item.ui.image {
            background: none !important;
        }

        .center.item,
        .center.item p,
        #nav-heading {
            pointer-events: none !important;
        }

            .center.item:hover,
            .center.item p:hover,
            #nav-heading:hover,
            .center.item:active,
            .center.item p:active,
            #nav-heading:active {
                color: inherit !important;
                text-decoration: none !important;
                background-color: transparent !important;
                box-shadow: none !important;
            }

    </style>
</head>

<body>
    <!-- Full width navigation menu -->
    <div class="ui top attached menu borderless">       

        <a class="item" href="~/" id="logo">
            <img class="item ui image" src="~/image/uci_logo.png" width="60px">
        </a>

        <div class="center item basic">
            <p class="ui text basic"><b id="nav-heading">Time Management System</b></p>
        </div>

        <div class="ui icon" id="notificationButton" aria-label="Notifications" style="margin-top: 21px; ">
            <i class="bell icon" style="font-size: 1.5em; "></i>
            <span class="notification-count" id="notificationCount"></span>
        </div>

        <div class="ui custom popup top transition hidden" id="notificationPopup">
            <div class="ui header" id="notificationHeader">Notifications</div>
            <div class="ui divider"></div>
            <div class="content" id="notification-Popup">
                <div class="ui relaxed divided list" id="notificationList">
                    <!-- Notification items will be dynamically added here -->
                </div>
            </div>
        </div>

        <div class="ui simple right item" id="userPopupTrigger">
            <!-- User icon that will trigger the popup -->
            <i class="user icon"></i>
            <span id="userDisplayName"></span>
        </div>

        <!-- Hidden content for the popup -->
        <div id="userPopupContent" style="display:none;">
            <div>
                <b>
                    <span id="popupUserName"></span>
                </b>
            </div>
            <div>
                <b>
                    <span id="popupUserEmail"></span>
                </b>
            </div>
        </div>

        <script>
            const navbar = {};

            // Function to handle the redirection
            navbar.handleRedirection = function () {
                const redirect = navbar.getQueryParam('redirect');
                if (redirect === "PendingApprovals") {
                    window.location.href = '/PendingApprovals';
                }
            }

            // Function to get the query
            navbar.getQueryParam = function (param) {
                const urlParams = new URLSearchParams(window.location.search);
                return urlParams.get(param);
            }

            navbar.checkHeartbeat = function () {
                fetch('/Routing/hb')
                    .then(response => response.json())
                    .then(response => {
                        if (!response.ok) {
                            window.location.href = '/';
                        }
                    });
            };

            navbar.setInterval = function () {
                setInterval(navbar.checkHeartbeat, 30000);
            };

            navbar.loadUserInfo = function () {
                fetch('api/User/GetCurrentUserInfo')
                    .then(response => response.json())
                    .then(data => {
                        $('#userDisplayName').text(data.username);
                        $('#popupUserName').text(data.username);
                        $('#popupUserEmail').text(data.email);
                        $('#nav-heading').text(data.envVar);
                    });
            }

            $(document).ready(function () {
                // Fomantic UI Popup Initialization
                $('#userPopupTrigger').popup({
                    popup: $('#userPopupContent'),
                    on: 'hover', // Trigger popup on hover
                    position: 'bottom center',
                    lastResort: 'bottom center',
                    hoverable: true, // Keeps the popup open when hovered over
                });

                navbar.loadUserInfo();
                navbar.setInterval();
                navbar.handleRedirection();
                notification.resetNotificationCount();
            });
        </script>
    </div>
</body>
</html>

Views/Shared/_PageLock.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<style>
    #pageLoader {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: rgba(255, 255, 255, 0.8);
        z-index: 9999;
        display: none;
        justify-content: center;
        align-items: center;
    }

     #pageLoader .ui.loader {
            font-size: 2rem;
     }


      #pageLoader p {
            text-align: center;
            margin-top: 10px;
            font-size: 30px;
            color: #555;
            position: absolute;
            top: 60%;
            left: 50%;
            transform: translate(-50%, -50%);
      }


</style>

<script>
    function _lockpage(msg) {
        if (!_.isUndefined(msg)) {
            $("#lockpagemessage").html(msg);
        }
        else {
            $("#lockpagemessage").html("Loading...");
        }
        $('#pageLoader').fadeIn();
    }

    function _unlockpage() {
        $('#pageLoader').fadeOut();
    }
</script>

<!-- Page Loader -->
<div id="pageLoader">
    <div class="ui active large loader"></div>
    <p id="lockpagemessage">Loading</p>
</div>

Views/Shared/_Sidebar.cshtml
<style>
    header {
        font-size: 1.5em;
    }

    .item {
        font-size: 1.2em; 
    }

    .ui.vertical.menu {
        width: 17rem;
    }

    .ui.menu {
        margin: 0;
    }
</style>

<div class="ui vertical menu">
    <div class="item">
        <div class="header x-large">HR Admin</div>
        <div class="menu">
            <a class="item huge" asp-area="" asp-controller="Home" asp-action="Index">
                <i class="bars icon"></i> HR Admin Dashboard
            </a>
            <a class="item huge" asp-area="" asp-controller="asdf" asp-action="asdf">
                <i class="file alternate icon"></i> Approval Status
            </a>
            <a class="item huge" asp-area="" asp-controller="HRAdmin" asp-action="AssignApprover">
                <i class="users icon"></i> Assign Approver
            </a>
            <a class="item huge" asp-area="" asp-controller="" asp-action="">
                <i class="tasks icon"></i> Engagement Status
            </a>
        </div>
    </div>

    <div class="item">
        <div class="header huge">Reporting Manager</div>
        <div class="menu">
            <a class="item huge" asp-area="" asp-controller="Home" asp-action="Index">
                <i class="bars icon"></i> Manager Dashboard
            </a>
            <a class="item huge" asp-area="" asp-controller="" asp-action="">
                <i class="file alternate icon"></i> Pending Approval
            </a>
            <a class="item huge" asp-area="" asp-controller="" asp-action="">
                <i class="users icon"></i> Approved Timesheets
            </a>
            <a class="item huge" asp-area="" asp-controller="" asp-action="">
                <i class="tasks icon"></i> Manage My Engagements
            </a>
        </div>
    </div>

    <div class="item">
        <div class="header huge">Employee</div>
        <div class="menu">
            <a class="item huge" asp-area="" asp-controller="Home" asp-action="Index">
                <i class="bars icon"></i> Employee Dashboard
            </a>
            <a class="item huge" asp-area="" asp-controller="" asp-action="">
                <i class="file alternate icon"></i> Add new Timesheet
            </a>
            <a class="item huge" asp-area="" asp-controller="" asp-action="">
                <i class="users icon"></i> View Previous Timesheets
            </a>
            <a class="item huge" asp-area="" asp-controller="" asp-action="">
                <i class="tasks icon"></i> My Engagements
            </a>
        </div>
    </div>
</div>